### ISSUE TITLE
Unable to run migrations

### ISSUE THREAD

**Issue by mukesh-o** [AmishFaldu/Tivix-NodeJS-Task#1]
Hey @AmishFaldu 

My pg connecting string `postgres://postgres:mukesh@localhost:5432/amish_nestjs`

When I start server locally database is connected, I don't see any error of database connection. But when I try to run migrations I see an error from postgres.

Not sure if typoorm requires me to change anything in my postgres config files 
Postgres version 14.2

![Screenshot 2022-05-09 at 12 28 41 PM](https://user-images.githubusercontent.com/69344163/167356740-707d2df7-bdb9-421e-811f-cfa39e91034c.png)

**Comment by AmishFaldu** [comment]
Hi @mukesh-o
You will need to change the ormconfig.ts file present in the root folder of the project to match your database configurations.

The thing is that to run/generate typeorm migration you need to pass in the configuration of database in cli
